### PR TITLE
Upgrade Steal

### PR DESCRIPTION
**Pull request by marshallswain**

### CODE REVIEW

**Comment by justinbmeyer** [comment]
I'm wary of making every test wait 50ms.  We should be able to figure out which test has the delay and fix it.

**Review by justinbmeyer — DISMISSED** [review]
Lets try to avoid 50 ms delay for every test.

**Comment by phillipskevin** [comment]
@justinbmeyer can you take another quick look at this? I removed the timeout entirely from the `teardown` and added timeouts to the tests that need them.

**Comment by marshallswain** [comment]
I'm going to merge this so we can move forward with the release.  If we want to investigate the timeouts further, let's make a separate issue for that.

**Pull request merged**
